### ISSUE TITLE
Editing/creating an entry and permission denied

### ISSUE THREAD

**Issue by compojoom** [rechenberger/firestore-query-browser#1]
The UI doesn't display an error when trying to craete/edit an entry and the current user doesn't have the sufficient permissions to do so.

**Comment by sean-nicholas** [comment]
Yeah, you're right. Cloud reproduce it. Will fix it

**Comment by sean-nicholas** [comment]
Changes are now live on: https://firestore-query-browser.firebaseapp.com/
Sorry for the late response. Didn't see this issue until now 🙈
