### ISSUE TITLE
Won't build in node 13.12.0 

### ISSUE THREAD

**Issue by crystalneth** [rechenberger/firestore-query-browser#4]
I did see someone having issues with building when Visual Studio Code is installed, so that might also be a factor. I am running macOS 10.15.4

node-gyp seems to be the culprit, which is a dependency of node-sass.

Here is the output of npm install:

https://gist.github.com/crystalneth/0c0c344966cfb602c86fb125a3f887f4

**Comment by sean-nicholas** [comment]
Can you remove the node_modules and the package-lock.json and try to reinstall it again? If this does not work tell me. Maybe the dependencies might need an update.

**Comment by sean-nicholas** [comment]
I'll close the issue for now. If you have any update let me know and reopen the issue.
