### ISSUE TITLE
How do I query with timestamp?

### ISSUE THREAD

**Issue by tnylee** [rechenberger/firestore-query-browser#8]
Hello and Thank you for this awesome library!

I'd like to filter my data with timestamp for example:

path:
`restaurants`

query:
```
ref
  .where('created', '>=', '2020-08-12T00:00:00.000Z')
  .orderBy('created', 'desc')
```

However the results are always empty. How can I filter the timestamp?

Thank you!

**Comment by tnylee** [comment]
I got it working by doing:

```
ref
  .where('created', '>=', new Date('2020-08-12T00:00'))
  .orderBy('created', 'desc')
```

**Comment by sean-nicholas** [comment]
Hey @tnylee,

thank you for your issue and I'm happy you could resolve it yourself. I updated the readme so others can find the info easily.
